### ISSUE TITLE
ペデスタルの測定結果

### ISSUE THREAD

**Issue by tomoe-y** [hmdyt/b4ex_plastic_scintillator#5]
- ペデスタルのグラフをヒストグラムに重ね書き

**Comment by hmdyt** [comment]
dev_hamadaにて重ね書きする関数を作成しました。
img内の画像を見てもらうとわかりますが、ぺデスタルのピークが高すぎて見栄えが悪いです。  
また、[これ](https://github.com/hmdyt/b4ex_plastic_scintillator/blob/dev_hamada/img/week1/led3021.rootCH29_Pedestal.pdf)などはぺデスタルの測定時に２つ目のピークが出ています。2つ目のピークが何かわからないと1つ目のピークがぺデスタルであると断言できず、どのピークがどのフォトン数であるか議論できないような気がします。
従って、以下の改善をお願いします。
- 見栄え悪い問題の解決
- 2つ目のピークが何か断定する
